### ISSUE TITLE
Elm 0.19.0 support

### ISSUE THREAD

**Issue by reesmichael1** [wunsh/docker-alpine-elm#1]
Thanks for this image! Would it be possible to update the included Elm version to `0.19.0` and put a corresponding tag on DockerHub?

**Comment by jarosluv** [comment]
@reesmichael1 Thanks for your feedback. Yes, I'll do it ASAP (today or tomorrow).

**Comment by jarosluv** [comment]
I need a little more time, thanks for waiting!

**Comment by jarosluv** [comment]
@reesmichael1 Please, check it out 0.19 release.

See available tags here https://hub.docker.com/r/wunsh/alpine-elm/tags/
